schema = 3

[mod]
  [mod."github.com/a-h/respond"]
    version = "v0.0.2"
    hash = "sha256-ymbnuFHpCuE7MwEJzY8uXGWHo/t0dqWzHFecaXThncs="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.17.1"
    hash = "sha256-KT/7xzUXjvYD4ZwM6IK5RnjMC+d9GjoYu5ZEIn/n4K8="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/go-github/v39"]
    version = "v39.2.0"
    hash = "sha256-rzMQo5Cnmky9zehUDaGrG2nL25hAd55jJe/efay04CM="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/rqlite/gorqlite"]
    version = "v0.0.0-20240227123050-397b03f02418"
    hash = "sha256-jrDn/TVR+1cmsciKAcjqAjwsy/pqOhjP4aonxy+6Gw4="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."golang.org/x/crypto"]
    version = "v0.20.0"
    hash = "sha256-7C0tDus5x3xRsSE08yOtZzMpOFym1Q9XP+U+CJ1sWmc="
  [mod."golang.org/x/net"]
    version = "v0.21.0"
    hash = "sha256-LfiqMpPtqvW/eLkfx6Ebr5ksqKbQli6uq06c/+XrBsw="
  [mod."golang.org/x/oauth2"]
    version = "v0.14.0"
    hash = "sha256-1wCXYvhtiGksL75rrOTDc6P82WuKBeaReqy1l7CahAE="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
